### ISSUE TITLE
Additional packages for packagesLibraries yaml

### ISSUE THREAD

**Issue by mjones01** [NEONInc/NEON-DataSkills-Lesson-Development#12]
Used in time series: 
L05: 
- scales
- grid Extra
- ggthemes

L06 & Culmination Activity: 
(scales & gridExtra again)
- grid
- reshape2

**Comment by lwasser** [comment]
cool. Do you suggest that we add them to our YAML list? If so please go ahead and add them to the YAML list but in the DEVELOPMENT SERVER. note that you are in the lesson dev site.

https://github.com/NEONInc/NEON-Data-Skills-Development/blob/gh-pages/_data/packagesLibraries.yml

Then add a .md file for each one here taking careful note to edit each .md file with the appropriate tags, etc. 

https://github.com/NEONInc/NEON-Data-Skills-Development/tree/gh-pages/org/packagesLibraries

 ps: I think we'll want to rename these repos so we don't get confused - let's do that together this week.

**Comment by mjones01** [comment]
Preference for Development server or template repo?  Task list specified Template repo, so I've started there (locally -- but can easily switch).  (accidentally did the issues here as I was looking at these YAML lists here).

**Comment by lwasser** [comment]
Good call - I realized this last night that we are on the path to confusion if we retain both the dev server and the template repo as is currently.  The content on the dev server is the most current because it is the only place that we can test to ensure it is working. I propose that we adjust our task list to implement on the dev server for the time being. The org files are most current there because I have to test there.

I am sorry for the confusion. Still working this out. I am happy to chat more in person tomorrow or Thursday or on the phone today if that is helpful. But the good news is that we can break anything on the dev server and it doesn't matter so I'm comfortable with working there!

Does that sound reasonable?

**Comment by mjones01** [comment]
Okay. My plan.  Add tag (phenology, change metadata-eml to metadata) & r packages (as above) to tags.yml and packages.yml .  Then adding .md files for each.  All is done in the Development server repo.

**Comment by lwasser** [comment]
Great - thank you!

**Comment by lwasser** [comment]
@mjones01 where is this PR? i don't see it in the dev server repo as mentioned above.

**Comment by mjones01** [comment]
The PR is now created: https://github.com/NEONInc/NEON-Data-Skills-Development/pull/1
