### ISSUE TITLE
Additional tags for Tags yaml

### ISSUE THREAD

**Issue by mjones01** [NEONInc/NEON-DataSkills-Lesson-Development#13]
Used in Time Series: 
- phenology @lwasser you suggested cutting this one but we will have many phenology themed lessons, especially once IS/OS lessons are done.  I support adding this one.  

Question: 
- metadata-eml  is this used solely for eml-type metadata or is it for metadata including eml?

**Comment by lwasser** [comment]
1. i think we should potentially add a science-tag list (a new YAML element) which will be separate from data skills tags. But if you want to add this as a tag for now to support existing functionality, i am all for that given we have "remote-sensing" as a tag too.

2. yes, we should change metadata-eml to just "metadata". it's a more appropriate tag.

If you want to add them 
1. edit the tags .ymL file here
https://github.com/NEONInc/NEON-Data-Skills-Development/blob/gh-pages/_data/tags.yml

2. add md files for each here:
https://github.com/NEONInc/NEON-Data-Skills-Development/tree/gh-pages/org/tag 

again note that is in the NDS DEV server not the LESSON DEV server where this issue is currently.

**Comment by mjones01** [comment]
Completed in Development server repo... Closing Issue.
